name = "rsmac"
compatibility_date = "2024-03-20"
pages_build_output_dir = "public"

[build]
command = ""
watch_dir = "public"

[site]
bucket = "public"
exclude = [
    "node_modules",
    ".wrangler",
    ".git",
    "package-lock.json",
    "package.json",
    "server.js",
    ".env",
    ".env.example"
]
